### ISSUE TITLE
Exception when attempting saving a class

### ISSUE THREAD

**Issue by cpurodriguez** [joshbirk/zen-compiler#1]
Hi, I created a project using mavensmate and I'm using zen-compiler to compile files on the run. 

I created an empty class called SlackTimelogWebhook.cls and when saving the file I'm getting the following error: 

```
SlackTimelogWebhook change detected (change). File is a Apex Class
timers.js:327
    throw new TypeError('"callback" argument must be a function');
    ^

TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:327:11)
    at /usr/local/lib/node_modules/zen-compiler/index.js:381:20
    at /usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/promise.js:72:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)```

**Comment by joshbirk** [comment]
It is a node version mismatch error.  I will put out the fix tomorrow
morning.

**Comment by joshbirk** [comment]
This should be fixed in 1.0.8, if you can confirm I'll close

**Comment by cpurodriguez** [comment]
@joshbirk it is working now - I have a weird issue when the first time I run zenc on an existing project, it is throwing a 

```
Logged into Salesforce instance https://cs41.salesforce.com with the access token XXXX
iCeL6O
Checking Container, please wait...
Container created.
{ INVALID_QUERY_FILTER_OPERATOR:
FROM ApexComponentMember WHERE MetadataContainerId = 'undefined'
                               ^
ERROR at Row:1:Column:69
invalid ID field: undefined
    at HttpApi.getError (/usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:250:13)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/zen-compiler/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'INVALID_QUERY_FILTER_OPERATOR',
  errorCode: 'INVALID_QUERY_FILTER_OPERATOR' }
{ INVALID_QUERY_FILTER_OPERATOR:
FullName FROM ApexPageMember WHERE MetadataContainerId = 'undefined'
                                   ^
ERROR at Row:1:Column:64
invalid ID field: undefined
    at HttpApi.getError (/usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:250:13)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/zen-compiler/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'INVALID_QUERY_FILTER_OPERATOR',
  errorCode: 'INVALID_QUERY_FILTER_OPERATOR' }
{ INVALID_QUERY_FILTER_OPERATOR:
FullName FROM ApexClassMember WHERE MetadataContainerId = 'undefined'
                                    ^
ERROR at Row:1:Column:65
invalid ID field: undefined
    at HttpApi.getError (/usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:250:13)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/zen-compiler/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'INVALID_QUERY_FILTER_OPERATOR',
  errorCode: 'INVALID_QUERY_FILTER_OPERATOR' }
{ INVALID_QUERY_FILTER_OPERATOR:
```

I need to exit zenc, and open again - then it works

**Comment by joshbirk** [comment]
Oh that is a weird one.  Let's close this issue and open a new one with that log file if you don't mind.  That's like the Tooling API said "I have a container" and then when asked for the ID it said "you can't have it".  It makes me wonder if the container got dismissed in mid-SOQL or something.

I'll add a check to the ID to insist it is valid, which should fix it - but it would be a hard one to replicate so might be good to leave a distinct issue open for a while to make sure it gets nailed down.

It should not be consistent, but if it is that's actually a good(ish) thing because then I can have you test the changes.
