### ISSUE TITLE
INVALID_QUERY_FILTER_OPERATOR when running zenc for the first time

### ISSUE THREAD

**Issue by cpurodriguez** [joshbirk/zen-compiler#2]
@joshbirk  I have a weird issue when the first time I run zenc on an existing project

```
Logged into Salesforce instance https://cs41.salesforce.com with the access token <TOKEN>
Checking Container, please wait...
Container created.
{ INVALID_QUERY_FILTER_OPERATOR:
FROM ApexComponentMember WHERE MetadataContainerId = 'undefined'
                               ^
ERROR at Row:1:Column:69
invalid ID field: undefined
    at HttpApi.getError (/usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:250:13)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/zen-compiler/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'INVALID_QUERY_FILTER_OPERATOR',
  errorCode: 'INVALID_QUERY_FILTER_OPERATOR' }
{ INVALID_QUERY_FILTER_OPERATOR:
FullName FROM ApexPageMember WHERE MetadataContainerId = 'undefined'
                                   ^
ERROR at Row:1:Column:64
invalid ID field: undefined
    at HttpApi.getError (/usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:250:13)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/zen-compiler/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'INVALID_QUERY_FILTER_OPERATOR',
  errorCode: 'INVALID_QUERY_FILTER_OPERATOR' }
{ INVALID_QUERY_FILTER_OPERATOR:
FullName FROM ApexClassMember WHERE MetadataContainerId = 'undefined'
                                    ^
ERROR at Row:1:Column:65
invalid ID field: undefined
    at HttpApi.getError (/usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:250:13)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/zen-compiler/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/zen-compiler/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'INVALID_QUERY_FILTER_OPERATOR',
  errorCode: 'INVALID_QUERY_FILTER_OPERATOR' }
{ INVALID_QUERY_FILTER_OPERATOR:

.....

```

**Comment by joshbirk** [comment]
Darn, thought I had commented on this much earlier.

So I can replicate this on some orgs.  It seems like it finds a dated meta container, but the id isn't valid so it gets dropped.  It should be resolvable in code once I can form the right catch.

For now the workaround is just re-run zen and it seems to work the second time.
